version: 2.1
orbs:
  docker: cirrus-labs/docker@2.6.1

jobs:
  build:
    executor: docker/build
    steps:
      - checkout
      - setup_remote_docker
      - docker build -t python-batchjob:job .
      - docker scan python-batchjob:job
