version: 2.1

jobs:
  build:
    docker:
      - image: quay.io/centos/centos:stream8

    working_directory: /app

    steps:
      - checkout

      # Install Podman
      - run:
          name: Install Podman
          command: |
            dnf install -y podman

      # Build the Docker image
      - run:
          name: Build Docker image
          command: |
            podman build -t quay.io/hemanth22/python_batchjob:job .

      # Login to Quay.io
      - run:
          name: Log in to Quay.io
          command: |
            podman login -u $QUAY_USERNAME -p $QUAY_PASSWORD quay.io

      # Push the Docker image to Quay.io
      - run:
          name: Push Docker image to Quay.io
          command: |
            podman push quay.io/hemanth22/python_batchjob:job
